config/routes.rb
Rails.application.routes.draw do

  
  post 'orders/:cart_id/create/' => 'orders#create', as: 'orders_create'
  get 'orders/show'
  get 'orders/index'

  post 'items/:dish_id/create' => 'items#create', as: 'items_create'
  put 'items/:item_id/update/:operation' => 'items#update', as: 'items_update'
  delete 'items/:item_id/destroy/:cart_id' => 'items#destroy', as: 'items_destroy'

  devise_for :users
  root 'restaurants#index'

  get 'restaurants/:id/show' => 'restaurants#show', as: 'restaurants_show'
  get 'dishes/:id/show' => 'dishes#show', as: 'dishes_show'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
	belongs_to :user
	belongs_to :restaurant
	has_many :items, dependent: :destroy
end

app/models/dish.rb
class Dish < ApplicationRecord
	belongs_to :restaurant
	has_one_attached :image
	# validates :image,  file_content_type: { allow: ['image/jpeg', 'image/gif', 'image/png'] }
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :cart
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	has_many :dishes
	has_many :carts
	has_one_attached :image
	# validates :image,  file_content_type: { allow: ['image/jpeg', 'image/gif', 'image/png'] }
end

app/models/story.rb
class Story < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :carts
	has_many :stories
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

	private

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :surname, :phone_number, :adress])
	end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  def show
  	@dish = Dish.find(params[:id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
  	@dish = Dish.find(params[:dish_id])
  	@cart = Cart.find_by(restaurant_id: @dish.restaurant.id, user_id: current_user.id)
  	if Item.find_by(title: @dish.title, price: @dish.price,  restaurant: @dish.restaurant.title, cart_id: @cart.id)
  		redirect_to restaurants_show_path(@dish.restaurant.id)
  	else
  		Item.create(title: @dish.title, price: @dish.price, qty: 1, restaurant: @dish.restaurant.title, cart_id: @cart.id)
  		redirect_to restaurants_show_path(@dish.restaurant.id)
  	end
  end

  def update
  	@item = Item.find(params[:item_id])
  	if params[:operation] == "plus"
      @item.update_attributes(qty: @item.qty += 1)
    elsif params[:operation] == "minus"
      if @item.qty > 1
       @item.update_attributes(qty: @item.qty -= 1)
      else
      end
   end
   redirect_to restaurants_show_path(@item.cart.restaurant.id)
 end

 def destroy
   @item = Item.find(params[:item_id])
   @cart = Cart.find_by(params[:cart_id])
   @item.destroy
   redirect_to restaurants_show_path(@cart.restaurant.id)
 end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
  	@cart = Cart.find_by(params[:cart_id])
  	goods = ""
  	@cart.items.each do |item|
  		goods += "|#{item.title} X #{item.qty}|"
  	end
  	Order.create(client_id: current_user.id, ordered: goods)
    Cart.find_by(params[:cart_id]).destroy
  	redirect_to root_path
  end

  def index
  	@orders = Order.all.where(client_id: current_user.id)
  end

  def show
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
  	@restaurants = Restaurant.all
  end

  def show
  	@restaurant = Restaurant.find(params[:id])
  	if Cart.find_by(user_id: current_user.id, restaurant_id: @restaurant.id)
  		@cart = Cart.find_by(user_id: current_user.id, restaurant_id: @restaurant.id)
  	else
		  @cart = Cart.create(user_id: current_user.id, restaurant_id: @restaurant.id)
	  end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def total_price(array)
		sum = 0
		array.each do |item|
			sum += (item.qty * item.price)
		end
		return sum
	end
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/dishes/show.html.erb
<h1><%= @dish.title %></h1>
<p><%= @dish.desc %></p>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodDelivery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/application/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application/_navbar.html.erb
<div style="height: 100px; background-color: lightgreen; text-align: center;">
	<% if user_signed_in? %>
		Hello, <%= current_user.first_name %> | 
		<%= link_to 'Редактировать профиль', edit_user_registration_path(current_user.id) %> | 
		<%= link_to 'Выйти из системы', destroy_user_session_path, method: :delete %> | 
		<%= link_to 'История ваших заказов', orders_index_path %>
	<% else %>
		<%= link_to 'Зарегистрироваться в системе', new_user_registration_path %> | 
		<%= link_to 'Войти в систему', new_user_session_path %>
	<% end %>
</div>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<% if @orders.all.count == 0 %>
	<p>Your order list is empty!</p>
<% else %>
	<h1>Your orders</h1>
	<ol>
		<% @orders.each do |order| %>
		<li><%= order.ordered %> | <%= order.created_at %></li>	
		<% end %>
	</ol>
<% end %>

<%= link_to "Back to main", root_path %>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/restaurants/index.html.erb
<% if Restaurant.all.count == 0 %>
	<h1>There are still no restaurants in our database!</h1>
<% else %>
	<% if user_signed_in? %>
		<h1 style="text-align: center;">Restaurants:</h1>
		<% @restaurants.each do |restaurant| %>
			<p class="text-sm-center">
				<% if restaurant.image.attached? %>
					<%= image_tag restaurant.image, size: 100 %>
				<% end %><br>
				<%= link_to restaurant.title, restaurants_show_path(restaurant.id) %>
			</p>
		<% end %>
	<% else %>
		<h1 style="text-align: center;">Registrate and log in to make an order!</h1>
		<% @restaurants.each do |restaurant| %>
			<p class="text-sm-center">
				<%= "*" * 50 %><br>
				<% if restaurant.image.attached? %>
					<%= image_tag restaurant.image, size: 100 %>
				<% end %><br>
				<%= "#{restaurant.title}" %><br>
				<%= "*" * 50 %>
			</p>
		<% end %>
	<% end %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.title %></h1>
<p><%= @restaurant.desc %></p>

<% if Cart.find_by(restaurant_id: @restaurant.id, user_id: current_user.id).items.count == 0 %>
	<div style="width: auto; height: auto; background-color: rgba(0,0,0,0.25);  position: fixed; right: 0px; padding: 15px; border-radius: 100%;">
		Your cart is empty<br>
	</div>
<% else %>
	<% @cart = Cart.find_by(restaurant_id: @restaurant.id, user_id: current_user.id) %>
	<div style="max-width: 50%; height: auto; background-color: rgba(0,0,0,0.25);  position: fixed; right: 0px; padding: 10px; border-radius: 10px;">
		<% @cart.items.each do |item| %>
			<%= "#{item.title} * #{item.qty} = #{item.price * item.qty}" %> |
			<%= link_to "Добавить", items_update_path(item.id, "plus"), method: :put %> | 
			<%= link_to "Убавить", items_update_path(item.id, "minus"), method: :put %> | 
			<%= link_to "Удалить", items_destroy_path(item.id, @cart.id), method: :delete %>
			<br>
		<% end %>
		Total price: <%= total_price(@cart.items) %> | <%= link_to "Сделать заказ", orders_create_path(@cart.id), method: :post %>
	</div>
<% end %>

<% if @restaurant.dishes.all.count == 0 %>
	<p>There are still no dishes in this restaurant!</p>
<% else %>
	<% @restaurant.dishes.each do |dish| %>
		<% if dish.image.attached? %>
			<%= image_tag dish.image, size: 100 %>
		<% end %>
		<h3>
			<%= link_to dish.title, dishes_show_path(dish.id) %> | 
			<%= dish.price %> | 
			<%= link_to "Добавить в Вашу корзину", items_create_path(dish.id), method: :post %> 
		</h3><br>
	<% end %>
<% end %>

<%= link_to "Main menu", root_path %>